server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root1234
    url: jdbc:mysql://localhost:3306/journal?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true

cloudinary:
 api-key: ${API_KEY}
 api-secret: ${SECRET}
 cloud-name: dxwfwbxq2


social:
 facebook:
  appId: ${APP_ID}
  appSecret: ${API_SECRET}
